In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.debugging.set_log_device_placement(True)

In [3]:
x0 = tf.constant(3)

x0

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [4]:
result0 = x0 + 5
result0

Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [5]:
x1 = tf.constant([1.1,2.2,3.3,4.4])

x1

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.1, 2.2, 3.3, 4.4], dtype=float32)>

In [6]:
result1 = x1 + tf.constant(5.0)

result1


Executing op AddV2 in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [7]:
result1 = tf.add(x1,tf.constant(5.0))

result1

Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Tensor: shape=(4,), dtype=float32, numpy=array([6.1, 7.2, 8.3, 9.4], dtype=float32)>

In [8]:
x2 = tf.constant([[1,2,3,4], [5,6,7,8]])
x2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])>

In [10]:
arr_1 = x1.numpy()

arr_1

array([1.1, 2.2, 3.3, 4.4], dtype=float32)

In [13]:
arr_x4 = np.array([[10,20], [30,40],[50,60]])

arr_x4

array([[10, 20],
       [30, 40],
       [50, 60]])

In [15]:
x4 = tf.convert_to_tensor(arr_x4)

x4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]])>

In [17]:
tf.is_tensor(x4)

True

In [19]:
v1 = tf.Variable([[1,2,3],[4,5,6]])
v2 = tf.Variable([[1,2,3],[4,5,6]])
tf.add(v1,v2)

Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarHandleOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op VarIsInitializedOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op LogicalNot in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Assert in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op AssignVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Add in de

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]])>

In [20]:
v1.assign_add([[1,1,1],[1,1,1]])

v1

Executing op AssignAddVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op ReadVariableOp in device /job:localhost/replica:0/task:0/device:CPU:0
Executing op Identity in device /job:localhost/replica:0/task:0/device:CPU:0


<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 4],
       [5, 6, 7]])>

In [21]:
tf.compat.v1.executing_eagerly()

True

In [23]:
a = tf.constant(5,name='a')
b = tf.constant(7,name='b')

c = tf.add(a,b,name='sum')

Executing op Add in device /job:localhost/replica:0/task:0/device:CPU:0


In [24]:
session = tf.compat.v1.Session()
session.run(c)

Device mapping: no known devices.


RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

In [25]:
c

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [26]:
tf.compat.v1.disable_eager_execution()
tf.compat.v1.executing_eagerly()

False

In [27]:
tf.compat.v1.reset_default_graph()

In [37]:
a = tf.constant(5,name='a')
b = tf.constant(7, tf.float32,name='b')

c = tf.add(a,b,name='sum')

TypeError: Input 'y' of 'Add' Op has type float32 that does not match type int32 of argument 'x'.

In [29]:
c

<tf.Tensor 'sum:0' shape=() dtype=int32>

In [30]:
session = tf.compat.v1.Session()
session.run(c)

Device mapping: no known devices.


12

In [31]:
d = tf.multiply(a,b,name='product')
session.run(d)

35

In [32]:
session.close()

In [33]:
m = tf.Variable([4.0,5.0,6.0], tf.float32,name='m')
c = tf.Variable([1.0,1.0,1.0], tf.float32,name='c')

In [34]:
m

<tf.Variable 'm:0' shape=(3,) dtype=float32>

In [35]:
x = tf.compat.v1.placeholder(tf.float32,shape=[3],name='x')
x

<tf.Tensor 'x:0' shape=(3,) dtype=float32>

In [38]:
y = m * x + b

y

<tf.Tensor 'add_1:0' shape=(3,) dtype=float32>

In [ ]:
init = tf.compat.v1.global_variables_initializer()